FROM rockylinux:9

RUN dnf -y install bash-completion glibc-langpack-en

COPY xsos /usr/local/bin/xsos
COPY xsos-bash-completion.bash /etc/profile.d/xsos-bash-completion.bash

RUN mkdir /sosreport

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]